import type {
  Difficulty,
  EquipmentSlug,
  ExerciseKind,
  MovementPattern,
  MuscleSlug,
} from './catalog.types.js';

export interface CatalogSeedExercise {
  name: string;
  slug: string;
  primaryMuscle: MuscleSlug;
  secondaryMuscles: MuscleSlug[];
  equipment: EquipmentSlug;
  pattern: MovementPattern;
  kind: ExerciseKind;
  difficulty: Difficulty;
  aliases: string[];
}

export const CATALOG_SEED: CatalogSeedExercise[] = [
  { name: 'Barbell Bench Press', slug: 'barbell-bench-press', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], equipment: 'barbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'intermediate', aliases: ['bench', 'bb bench'] },
  { name: 'Incline Barbell Bench Press', slug: 'incline-barbell-bench-press', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], equipment: 'barbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'intermediate', aliases: ['incline bench'] },
  { name: 'Decline Barbell Bench Press', slug: 'decline-barbell-bench-press', primaryMuscle: 'chest', secondaryMuscles: ['triceps'], equipment: 'barbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'intermediate', aliases: ['decline bench'] },
  { name: 'Dumbbell Bench Press', slug: 'dumbbell-bench-press', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], equipment: 'dumbbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'beginner', aliases: ['db bench'] },
  { name: 'Incline Dumbbell Press', slug: 'incline-dumbbell-press', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], equipment: 'dumbbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'beginner', aliases: ['incline db'] },
  { name: 'Decline Dumbbell Press', slug: 'decline-dumbbell-press', primaryMuscle: 'chest', secondaryMuscles: ['triceps'], equipment: 'dumbbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'intermediate', aliases: ['decline db'] },
  { name: 'Machine Chest Press', slug: 'machine-chest-press', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], equipment: 'machine', pattern: 'horizontal-push', kind: 'compound', difficulty: 'beginner', aliases: ['chest press'] },
  { name: 'Cable Chest Fly', slug: 'cable-chest-fly', primaryMuscle: 'chest', secondaryMuscles: ['front-delts'], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['cable fly', 'flyes'] },
  { name: 'Pec Deck', slug: 'pec-deck', primaryMuscle: 'chest', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['pec deck fly'] },
  { name: 'Push-Up', slug: 'push-up', primaryMuscle: 'chest', secondaryMuscles: ['front-delts', 'triceps'], equipment: 'bodyweight', pattern: 'horizontal-push', kind: 'compound', difficulty: 'beginner', aliases: ['pushup', 'push ups'] },
  { name: 'Chest Dip', slug: 'chest-dip', primaryMuscle: 'chest', secondaryMuscles: ['triceps', 'front-delts'], equipment: 'bodyweight', pattern: 'vertical-push', kind: 'compound', difficulty: 'intermediate', aliases: ['dips'] },
  { name: 'Floor Press', slug: 'floor-press', primaryMuscle: 'chest', secondaryMuscles: ['triceps'], equipment: 'barbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'intermediate', aliases: ['bb floor press'] },
  { name: 'Overhead Press', slug: 'overhead-press', primaryMuscle: 'front-delts', secondaryMuscles: ['triceps', 'side-delts'], equipment: 'barbell', pattern: 'vertical-push', kind: 'compound', difficulty: 'intermediate', aliases: ['ohp', 'military press'] },
  { name: 'Seated Dumbbell Press', slug: 'seated-dumbbell-press', primaryMuscle: 'front-delts', secondaryMuscles: ['triceps', 'side-delts'], equipment: 'dumbbell', pattern: 'vertical-push', kind: 'compound', difficulty: 'beginner', aliases: ['db press'] },
  { name: 'Arnold Press', slug: 'arnold-press', primaryMuscle: 'front-delts', secondaryMuscles: ['side-delts', 'triceps'], equipment: 'dumbbell', pattern: 'vertical-push', kind: 'compound', difficulty: 'intermediate', aliases: ['arnold'] },
  { name: 'Front Raise', slug: 'front-raise', primaryMuscle: 'front-delts', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['db front raise'] },
  { name: 'Landmine Press', slug: 'landmine-press', primaryMuscle: 'front-delts', secondaryMuscles: ['chest', 'triceps'], equipment: 'barbell', pattern: 'vertical-push', kind: 'compound', difficulty: 'beginner', aliases: ['landmine'] },
  { name: 'Push Press', slug: 'push-press', primaryMuscle: 'front-delts', secondaryMuscles: ['triceps', 'quads'], equipment: 'barbell', pattern: 'vertical-push', kind: 'compound', difficulty: 'advanced', aliases: ['push press'] },
  { name: 'Dumbbell Lateral Raise', slug: 'dumbbell-lateral-raise', primaryMuscle: 'side-delts', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['lateral raise', 'side raise'] },
  { name: 'Cable Lateral Raise', slug: 'cable-lateral-raise', primaryMuscle: 'side-delts', secondaryMuscles: [], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['cable side raise'] },
  { name: 'Machine Lateral Raise', slug: 'machine-lateral-raise', primaryMuscle: 'side-delts', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['machine raise'] },
  { name: 'Upright Row', slug: 'upright-row', primaryMuscle: 'side-delts', secondaryMuscles: ['traps'], equipment: 'barbell', pattern: 'vertical-pull', kind: 'compound', difficulty: 'intermediate', aliases: ['bb upright row'] },
  { name: 'Lean-Away Lateral Raise', slug: 'lean-away-lateral-raise', primaryMuscle: 'side-delts', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'intermediate', aliases: ['lean away raise'] },
  { name: 'Face Pull', slug: 'face-pull', primaryMuscle: 'rear-delts', secondaryMuscles: ['traps', 'upper-back'], equipment: 'cable', pattern: 'horizontal-pull', kind: 'isolation', difficulty: 'beginner', aliases: ['facepulls', 'face pulls'] },
  { name: 'Rear Delt Fly', slug: 'rear-delt-fly', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['reverse fly'] },
  { name: 'Reverse Pec Deck', slug: 'reverse-pec-deck', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['reverse pec deck'] },
  { name: 'Bent-Over Reverse Fly', slug: 'bent-over-reverse-fly', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['bent reverse fly'] },
  { name: 'Band Pull-Apart', slug: 'band-pull-apart', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], equipment: 'band', pattern: 'horizontal-pull', kind: 'isolation', difficulty: 'beginner', aliases: ['pull apart'] },
  { name: 'Pull-Up', slug: 'pull-up', primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'upper-back'], equipment: 'bodyweight', pattern: 'vertical-pull', kind: 'compound', difficulty: 'intermediate', aliases: ['pullup', 'pull ups'] },
  { name: 'Chin-Up', slug: 'chin-up', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], equipment: 'bodyweight', pattern: 'vertical-pull', kind: 'compound', difficulty: 'intermediate', aliases: ['chinup'] },
  { name: 'Lat Pulldown', slug: 'lat-pulldown', primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'upper-back'], equipment: 'cable', pattern: 'vertical-pull', kind: 'compound', difficulty: 'beginner', aliases: ['pulldown', 'lat pull down'] },
  { name: 'Close-Grip Lat Pulldown', slug: 'close-grip-lat-pulldown', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], equipment: 'cable', pattern: 'vertical-pull', kind: 'compound', difficulty: 'beginner', aliases: ['close grip pulldown'] },
  { name: 'Straight-Arm Pulldown', slug: 'straight-arm-pulldown', primaryMuscle: 'lats', secondaryMuscles: [], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['stiff arm pulldown'] },
  { name: 'Dumbbell Pullover', slug: 'dumbbell-pullover', primaryMuscle: 'lats', secondaryMuscles: ['chest'], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['pullover'] },
  { name: 'Single-Arm Lat Pulldown', slug: 'single-arm-lat-pulldown', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], equipment: 'cable', pattern: 'vertical-pull', kind: 'compound', difficulty: 'beginner', aliases: ['one arm pulldown'] },
  { name: 'Assisted Pull-Up', slug: 'assisted-pull-up', primaryMuscle: 'lats', secondaryMuscles: ['biceps'], equipment: 'machine', pattern: 'vertical-pull', kind: 'compound', difficulty: 'beginner', aliases: ['assisted pullup'] },
  { name: 'Barbell Row', slug: 'barbell-row', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps', 'lower-back'], equipment: 'barbell', pattern: 'horizontal-pull', kind: 'compound', difficulty: 'intermediate', aliases: ['bb row', 'bent over row'] },
  { name: 'Pendlay Row', slug: 'pendlay-row', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], equipment: 'barbell', pattern: 'horizontal-pull', kind: 'compound', difficulty: 'advanced', aliases: ['pendlay'] },
  { name: 'Seated Cable Row', slug: 'seated-cable-row', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], equipment: 'cable', pattern: 'horizontal-pull', kind: 'compound', difficulty: 'beginner', aliases: ['cable row', 'seated row'] },
  { name: 'Chest-Supported Row', slug: 'chest-supported-row', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], equipment: 'machine', pattern: 'horizontal-pull', kind: 'compound', difficulty: 'beginner', aliases: ['supported row'] },
  { name: 'T-Bar Row', slug: 't-bar-row', primaryMuscle: 'upper-back', secondaryMuscles: ['lats', 'biceps'], equipment: 'barbell', pattern: 'horizontal-pull', kind: 'compound', difficulty: 'intermediate', aliases: ['tbar row'] },
  { name: 'Meadows Row', slug: 'meadows-row', primaryMuscle: 'upper-back', secondaryMuscles: ['lats'], equipment: 'barbell', pattern: 'horizontal-pull', kind: 'compound', difficulty: 'advanced', aliases: ['landmine row'] },
  { name: 'Inverted Row', slug: 'inverted-row', primaryMuscle: 'upper-back', secondaryMuscles: ['biceps'], equipment: 'bodyweight', pattern: 'horizontal-pull', kind: 'compound', difficulty: 'beginner', aliases: ['bodyweight row'] },
  { name: 'Barbell Shrug', slug: 'barbell-shrug', primaryMuscle: 'traps', secondaryMuscles: [], equipment: 'barbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['bb shrug'] },
  { name: 'Dumbbell Shrug', slug: 'dumbbell-shrug', primaryMuscle: 'traps', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['db shrug'] },
  { name: 'Farmer Carry', slug: 'farmer-carry', primaryMuscle: 'traps', secondaryMuscles: ['forearms', 'abs'], equipment: 'dumbbell', pattern: 'carry', kind: 'compound', difficulty: 'beginner', aliases: ['farmers walk', 'farmer walk'] },
  { name: 'Conventional Deadlift', slug: 'conventional-deadlift', primaryMuscle: 'lower-back', secondaryMuscles: ['hamstrings', 'glutes', 'traps'], equipment: 'barbell', pattern: 'hinge', kind: 'compound', difficulty: 'intermediate', aliases: ['deadlift', 'dl'] },
  { name: 'Romanian Deadlift', slug: 'romanian-deadlift', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes', 'lower-back'], equipment: 'barbell', pattern: 'hinge', kind: 'compound', difficulty: 'intermediate', aliases: ['rdl'] },
  { name: 'Back Extension', slug: 'back-extension', primaryMuscle: 'lower-back', secondaryMuscles: ['glutes'], equipment: 'machine', pattern: 'hinge', kind: 'isolation', difficulty: 'beginner', aliases: ['hyperextension'] },
  { name: 'Good Morning', slug: 'good-morning', primaryMuscle: 'lower-back', secondaryMuscles: ['hamstrings'], equipment: 'barbell', pattern: 'hinge', kind: 'compound', difficulty: 'advanced', aliases: ['goodmornings'] },
  { name: 'Barbell Curl', slug: 'barbell-curl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], equipment: 'barbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['bb curl'] },
  { name: 'EZ-Bar Curl', slug: 'ez-bar-curl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], equipment: 'barbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['ez curl'] },
  { name: 'Dumbbell Curl', slug: 'dumbbell-curl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['db curl'] },
  { name: 'Hammer Curl', slug: 'hammer-curl', primaryMuscle: 'biceps', secondaryMuscles: ['forearms'], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['hammer curls'] },
  { name: 'Incline Dumbbell Curl', slug: 'incline-dumbbell-curl', primaryMuscle: 'biceps', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['incline curl'] },
  { name: 'Preacher Curl', slug: 'preacher-curl', primaryMuscle: 'biceps', secondaryMuscles: [], equipment: 'barbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['preacher'] },
  { name: 'Cable Curl', slug: 'cable-curl', primaryMuscle: 'biceps', secondaryMuscles: [], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['cable curls'] },
  { name: 'Concentration Curl', slug: 'concentration-curl', primaryMuscle: 'biceps', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['concentration'] },
  { name: 'Close-Grip Bench Press', slug: 'close-grip-bench-press', primaryMuscle: 'triceps', secondaryMuscles: ['chest'], equipment: 'barbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'intermediate', aliases: ['cg bench'] },
  { name: 'Tricep Pushdown', slug: 'tricep-pushdown', primaryMuscle: 'triceps', secondaryMuscles: [], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['pushdown'] },
  { name: 'Overhead Tricep Extension', slug: 'overhead-tricep-extension', primaryMuscle: 'triceps', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['oh extension'] },
  { name: 'Skull Crusher', slug: 'skull-crusher', primaryMuscle: 'triceps', secondaryMuscles: [], equipment: 'barbell', pattern: 'isolation', kind: 'isolation', difficulty: 'intermediate', aliases: ['lying extension'] },
  { name: 'Tricep Dip', slug: 'tricep-dip', primaryMuscle: 'triceps', secondaryMuscles: ['chest', 'front-delts'], equipment: 'bodyweight', pattern: 'vertical-push', kind: 'compound', difficulty: 'intermediate', aliases: ['bench dip'] },
  { name: 'Tricep Kickback', slug: 'tricep-kickback', primaryMuscle: 'triceps', secondaryMuscles: [], equipment: 'dumbbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['kickback'] },
  { name: 'Rope Pushdown', slug: 'rope-pushdown', primaryMuscle: 'triceps', secondaryMuscles: [], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['rope extension'] },
  { name: 'JM Press', slug: 'jm-press', primaryMuscle: 'triceps', secondaryMuscles: ['chest'], equipment: 'barbell', pattern: 'horizontal-push', kind: 'compound', difficulty: 'advanced', aliases: ['jm press'] },
  { name: 'Wrist Curl', slug: 'wrist-curl', primaryMuscle: 'forearms', secondaryMuscles: [], equipment: 'barbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['wrist curls'] },
  { name: 'Reverse Wrist Curl', slug: 'reverse-wrist-curl', primaryMuscle: 'forearms', secondaryMuscles: [], equipment: 'barbell', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['reverse wrist'] },
  { name: 'Crunch', slug: 'crunch', primaryMuscle: 'abs', secondaryMuscles: [], equipment: 'bodyweight', pattern: 'core', kind: 'isolation', difficulty: 'beginner', aliases: ['crunches'] },
  { name: 'Hanging Leg Raise', slug: 'hanging-leg-raise', primaryMuscle: 'abs', secondaryMuscles: ['forearms'], equipment: 'bodyweight', pattern: 'core', kind: 'isolation', difficulty: 'intermediate', aliases: ['hlr'] },
  { name: 'Cable Crunch', slug: 'cable-crunch', primaryMuscle: 'abs', secondaryMuscles: [], equipment: 'cable', pattern: 'core', kind: 'isolation', difficulty: 'beginner', aliases: ['kneeling crunch'] },
  { name: 'Plank', slug: 'plank', primaryMuscle: 'abs', secondaryMuscles: [], equipment: 'bodyweight', pattern: 'core', kind: 'isolation', difficulty: 'beginner', aliases: ['front plank'] },
  { name: 'Ab Wheel Rollout', slug: 'ab-wheel-rollout', primaryMuscle: 'abs', secondaryMuscles: ['lats'], equipment: 'bodyweight', pattern: 'core', kind: 'compound', difficulty: 'advanced', aliases: ['ab wheel'] },
  { name: 'Russian Twist', slug: 'russian-twist', primaryMuscle: 'obliques', secondaryMuscles: ['abs'], equipment: 'bodyweight', pattern: 'rotation', kind: 'isolation', difficulty: 'beginner', aliases: ['twists'] },
  { name: 'Pallof Press', slug: 'pallof-press', primaryMuscle: 'obliques', secondaryMuscles: ['abs'], equipment: 'cable', pattern: 'core', kind: 'isolation', difficulty: 'beginner', aliases: ['pallof'] },
  { name: 'Hanging Knee Raise', slug: 'hanging-knee-raise', primaryMuscle: 'abs', secondaryMuscles: [], equipment: 'bodyweight', pattern: 'core', kind: 'isolation', difficulty: 'beginner', aliases: ['knee raise'] },
  { name: 'Back Squat', slug: 'back-squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes', 'lower-back'], equipment: 'barbell', pattern: 'squat', kind: 'compound', difficulty: 'intermediate', aliases: ['squat', 'bb squat'] },
  { name: 'Front Squat', slug: 'front-squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes', 'abs'], equipment: 'barbell', pattern: 'squat', kind: 'compound', difficulty: 'advanced', aliases: ['front squats'] },
  { name: 'Leg Press', slug: 'leg-press', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], equipment: 'machine', pattern: 'squat', kind: 'compound', difficulty: 'beginner', aliases: ['sled press'] },
  { name: 'Bulgarian Split Squat', slug: 'bulgarian-split-squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], equipment: 'dumbbell', pattern: 'lunge', kind: 'compound', difficulty: 'intermediate', aliases: ['bss'] },
  { name: 'Walking Lunge', slug: 'walking-lunge', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], equipment: 'dumbbell', pattern: 'lunge', kind: 'compound', difficulty: 'beginner', aliases: ['lunges'] },
  { name: 'Leg Extension', slug: 'leg-extension', primaryMuscle: 'quads', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['quad extension'] },
  { name: 'Goblet Squat', slug: 'goblet-squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], equipment: 'dumbbell', pattern: 'squat', kind: 'compound', difficulty: 'beginner', aliases: ['goblet'] },
  { name: 'Hack Squat', slug: 'hack-squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], equipment: 'machine', pattern: 'squat', kind: 'compound', difficulty: 'intermediate', aliases: ['hack'] },
  { name: 'Smith Squat', slug: 'smith-squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], equipment: 'smith', pattern: 'squat', kind: 'compound', difficulty: 'beginner', aliases: ['smith machine squat'] },
  { name: 'Lying Leg Curl', slug: 'lying-leg-curl', primaryMuscle: 'hamstrings', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['leg curl'] },
  { name: 'Seated Leg Curl', slug: 'seated-leg-curl', primaryMuscle: 'hamstrings', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['seated curl'] },
  { name: 'Nordic Curl', slug: 'nordic-curl', primaryMuscle: 'hamstrings', secondaryMuscles: [], equipment: 'bodyweight', pattern: 'hinge', kind: 'isolation', difficulty: 'advanced', aliases: ['nordic ham'] },
  { name: 'Stiff-Leg Deadlift', slug: 'stiff-leg-deadlift', primaryMuscle: 'hamstrings', secondaryMuscles: ['lower-back'], equipment: 'barbell', pattern: 'hinge', kind: 'compound', difficulty: 'intermediate', aliases: ['sldl'] },
  { name: 'Single-Leg RDL', slug: 'single-leg-rdl', primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes'], equipment: 'dumbbell', pattern: 'hinge', kind: 'compound', difficulty: 'intermediate', aliases: ['sl rdl'] },
  { name: 'Hip Thrust', slug: 'hip-thrust', primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings'], equipment: 'barbell', pattern: 'hinge', kind: 'compound', difficulty: 'beginner', aliases: ['barbell hip thrust'] },
  { name: 'Glute Bridge', slug: 'glute-bridge', primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings'], equipment: 'bodyweight', pattern: 'hinge', kind: 'isolation', difficulty: 'beginner', aliases: ['bridge'] },
  { name: 'Cable Kickback', slug: 'cable-kickback', primaryMuscle: 'glutes', secondaryMuscles: [], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['glute kickback'] },
  { name: 'Step-Up', slug: 'step-up', primaryMuscle: 'glutes', secondaryMuscles: ['quads'], equipment: 'dumbbell', pattern: 'lunge', kind: 'compound', difficulty: 'beginner', aliases: ['step ups'] },
  { name: 'Sumo Deadlift', slug: 'sumo-deadlift', primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings', 'quads'], equipment: 'barbell', pattern: 'hinge', kind: 'compound', difficulty: 'intermediate', aliases: ['sumo dl'] },
  { name: 'Standing Calf Raise', slug: 'standing-calf-raise', primaryMuscle: 'calves', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['calf raise'] },
  { name: 'Seated Calf Raise', slug: 'seated-calf-raise', primaryMuscle: 'calves', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['seated calves'] },
  { name: 'Donkey Calf Raise', slug: 'donkey-calf-raise', primaryMuscle: 'calves', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'intermediate', aliases: ['donkey calves'] },
  { name: 'Calf Press', slug: 'calf-press', primaryMuscle: 'calves', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['leg press calves'] },
  { name: 'Hip Adduction', slug: 'hip-adduction', primaryMuscle: 'adductors', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['adductor machine'] },
  { name: 'Hip Abduction', slug: 'hip-abduction', primaryMuscle: 'abductors', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['abductor machine'] },
  { name: 'Copenhagen Plank', slug: 'copenhagen-plank', primaryMuscle: 'adductors', secondaryMuscles: ['abs'], equipment: 'bodyweight', pattern: 'core', kind: 'isolation', difficulty: 'advanced', aliases: ['copenhagen'] },
  { name: 'Lateral Band Walk', slug: 'lateral-band-walk', primaryMuscle: 'abductors', secondaryMuscles: ['glutes'], equipment: 'band', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['monster walk'] },
  { name: 'Kettlebell Swing', slug: 'kettlebell-swing', primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings', 'abs'], equipment: 'kettlebell', pattern: 'hinge', kind: 'compound', difficulty: 'beginner', aliases: ['kb swing'] },
  { name: 'Kettlebell Goblet Squat', slug: 'kettlebell-goblet-squat', primaryMuscle: 'quads', secondaryMuscles: ['glutes'], equipment: 'kettlebell', pattern: 'squat', kind: 'compound', difficulty: 'beginner', aliases: ['kb goblet'] },
  { name: 'Smith Incline Press', slug: 'smith-incline-press', primaryMuscle: 'chest', secondaryMuscles: ['front-delts'], equipment: 'smith', pattern: 'horizontal-push', kind: 'compound', difficulty: 'beginner', aliases: ['smith incline'] },
  { name: 'Cable Row to Neck', slug: 'cable-row-to-neck', primaryMuscle: 'rear-delts', secondaryMuscles: ['upper-back'], equipment: 'cable', pattern: 'horizontal-pull', kind: 'isolation', difficulty: 'beginner', aliases: ['face row'] },
  { name: 'Machine Preacher Curl', slug: 'machine-preacher-curl', primaryMuscle: 'biceps', secondaryMuscles: [], equipment: 'machine', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['machine curl'] },
  { name: 'Overhead Cable Extension', slug: 'overhead-cable-extension', primaryMuscle: 'triceps', secondaryMuscles: [], equipment: 'cable', pattern: 'isolation', kind: 'isolation', difficulty: 'beginner', aliases: ['cable oh extension'] },
];
