export type CatalogExercise = {
  id: string;
  name: string;
  slug: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: string;
  pattern: string;
  type: string;
  difficulty: string;
};

export const MUSCLE_IDS = [
  'chest',
  'shoulders',
  'biceps',
  'triceps',
  'forearms',
  'abs',
  'obliques',
  'quads',
  'hamstrings',
  'glutes',
  'calves',
  'traps',
  'lats',
  'mid-back',
  'lower-back',
  'adductors',
  'neck',
] as const;

export type MuscleId = (typeof MUSCLE_IDS)[number];

export const REGION_PATTERNS: Record<string, string[]> = {
  chest: ['horizontal-press', 'fly'],
  shoulders: ['vertical-press', 'horizontal-press'],
  biceps: ['vertical-pull', 'isolation'],
  triceps: ['horizontal-press', 'vertical-press', 'isolation'],
  forearms: ['isolation', 'carry'],
  abs: ['core'],
  obliques: ['core'],
  quads: ['squat', 'lunge'],
  hamstrings: ['hinge', 'lunge'],
  glutes: ['hinge', 'squat'],
  calves: ['isolation'],
  traps: ['vertical-pull', 'hinge'],
  lats: ['vertical-pull', 'horizontal-pull'],
  'mid-back': ['horizontal-pull'],
  'lower-back': ['hinge'],
  adductors: ['squat', 'lunge'],
  neck: ['isolation'],
};

type Row = [
  slug: string,
  name: string,
  primary: string,
  secondary: string[],
  equipment: string,
  pattern: string,
  type: string,
  difficulty: string,
];

const ROWS: Row[] = [
  ['bench-press', 'Bench Press', 'chest', ['triceps', 'shoulders'], 'barbell', 'horizontal-press', 'compound', 'intermediate'],
  ['dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', ['triceps', 'shoulders'], 'dumbbell', 'horizontal-press', 'compound', 'beginner'],
  ['incline-bench-press', 'Incline Bench Press', 'chest', ['shoulders', 'triceps'], 'barbell', 'horizontal-press', 'compound', 'intermediate'],
  ['incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', ['shoulders', 'triceps'], 'dumbbell', 'horizontal-press', 'compound', 'beginner'],
  ['decline-bench-press', 'Decline Bench Press', 'chest', ['triceps'], 'barbell', 'horizontal-press', 'compound', 'intermediate'],
  ['machine-chest-press', 'Machine Chest Press', 'chest', ['triceps', 'shoulders'], 'machine', 'horizontal-press', 'compound', 'beginner'],
  ['push-ups', 'Push-ups', 'chest', ['triceps', 'shoulders', 'abs'], 'bodyweight', 'horizontal-press', 'compound', 'beginner'],
  ['chest-dip', 'Chest Dip', 'chest', ['triceps', 'shoulders'], 'bodyweight', 'horizontal-press', 'compound', 'intermediate'],
  ['cable-fly', 'Cable Fly', 'chest', ['shoulders'], 'cable', 'fly', 'isolation', 'beginner'],
  ['pec-deck', 'Pec Deck', 'chest', [], 'machine', 'fly', 'isolation', 'beginner'],
  ['dumbbell-fly', 'Dumbbell Fly', 'chest', ['shoulders'], 'dumbbell', 'fly', 'isolation', 'intermediate'],
  ['overhead-press', 'Overhead Press', 'shoulders', ['triceps', 'traps'], 'barbell', 'vertical-press', 'compound', 'intermediate'],
  ['dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'shoulders', ['triceps'], 'dumbbell', 'vertical-press', 'compound', 'beginner'],
  ['machine-shoulder-press', 'Machine Shoulder Press', 'shoulders', ['triceps'], 'machine', 'vertical-press', 'compound', 'beginner'],
  ['arnold-press', 'Arnold Press', 'shoulders', ['triceps'], 'dumbbell', 'vertical-press', 'compound', 'intermediate'],
  ['landmine-press', 'Landmine Press', 'shoulders', ['chest', 'triceps'], 'barbell', 'vertical-press', 'compound', 'beginner'],
  ['lateral-raise', 'Lateral Raise', 'shoulders', [], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['front-raise', 'Front Raise', 'shoulders', [], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['rear-delt-fly', 'Rear Delt Fly', 'shoulders', ['mid-back'], 'dumbbell', 'fly', 'isolation', 'beginner'],
  ['face-pull', 'Face Pull', 'shoulders', ['mid-back', 'traps'], 'cable', 'horizontal-pull', 'isolation', 'beginner'],
  ['upright-row', 'Upright Row', 'shoulders', ['traps'], 'barbell', 'vertical-pull', 'compound', 'intermediate'],
  ['tricep-pushdown', 'Tricep Pushdown', 'triceps', [], 'cable', 'isolation', 'isolation', 'beginner'],
  ['skull-crusher', 'Skull Crusher', 'triceps', [], 'barbell', 'isolation', 'isolation', 'intermediate'],
  ['overhead-tricep-extension', 'Overhead Tricep Extension', 'triceps', [], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['close-grip-bench', 'Close-Grip Bench Press', 'triceps', ['chest', 'shoulders'], 'barbell', 'horizontal-press', 'compound', 'intermediate'],
  ['bench-dip', 'Bench Dip', 'triceps', ['chest'], 'bodyweight', 'isolation', 'compound', 'beginner'],
  ['tricep-kickback', 'Tricep Kickback', 'triceps', [], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['barbell-curl', 'Barbell Curl', 'biceps', ['forearms'], 'barbell', 'isolation', 'isolation', 'beginner'],
  ['dumbbell-curl', 'Dumbbell Curl', 'biceps', ['forearms'], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['hammer-curl', 'Hammer Curl', 'biceps', ['forearms'], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['preacher-curl', 'Preacher Curl', 'biceps', [], 'barbell', 'isolation', 'isolation', 'beginner'],
  ['cable-curl', 'Cable Curl', 'biceps', [], 'cable', 'isolation', 'isolation', 'beginner'],
  ['concentration-curl', 'Concentration Curl', 'biceps', [], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['chin-up', 'Chin-up', 'biceps', ['lats', 'mid-back'], 'bodyweight', 'vertical-pull', 'compound', 'intermediate'],
  ['wrist-curl', 'Wrist Curl', 'forearms', [], 'dumbbell', 'isolation', 'isolation', 'beginner'],
  ['farmers-carry', "Farmer's Carry", 'forearms', ['traps', 'abs'], 'dumbbell', 'carry', 'compound', 'beginner'],
  ['barbell-row', 'Barbell Row', 'mid-back', ['lats', 'biceps', 'lower-back'], 'barbell', 'horizontal-pull', 'compound', 'intermediate'],
  ['dumbbell-row', 'Dumbbell Row', 'mid-back', ['lats', 'biceps'], 'dumbbell', 'horizontal-pull', 'compound', 'beginner'],
  ['seated-cable-row', 'Seated Cable Row', 'mid-back', ['lats', 'biceps'], 'cable', 'horizontal-pull', 'compound', 'beginner'],
  ['chest-supported-row', 'Chest-Supported Row', 'mid-back', ['lats', 'biceps'], 'dumbbell', 'horizontal-pull', 'compound', 'beginner'],
  ['inverted-row', 'Inverted Row', 'mid-back', ['lats', 'biceps'], 'bodyweight', 'horizontal-pull', 'compound', 'beginner'],
  ['pull-up', 'Pull-up', 'lats', ['biceps', 'mid-back'], 'bodyweight', 'vertical-pull', 'compound', 'intermediate'],
  ['lat-pulldown', 'Lat Pulldown', 'lats', ['biceps', 'mid-back'], 'cable', 'vertical-pull', 'compound', 'beginner'],
  ['straight-arm-pulldown', 'Straight-Arm Pulldown', 'lats', [], 'cable', 'isolation', 'isolation', 'beginner'],
  ['pullover', 'Dumbbell Pullover', 'lats', ['chest'], 'dumbbell', 'isolation', 'isolation', 'intermediate'],
  ['shrug', 'Barbell Shrug', 'traps', [], 'barbell', 'isolation', 'isolation', 'beginner'],
  ['rack-pull', 'Rack Pull', 'lower-back', ['traps', 'glutes', 'hamstrings'], 'barbell', 'hinge', 'compound', 'intermediate'],
  ['good-morning', 'Good Morning', 'lower-back', ['hamstrings', 'glutes'], 'barbell', 'hinge', 'compound', 'advanced'],
  ['reverse-fly', 'Reverse Fly', 'mid-back', ['shoulders'], 'dumbbell', 'fly', 'isolation', 'beginner'],
  ['back-squat', 'Back Squat', 'quads', ['glutes', 'adductors', 'lower-back'], 'barbell', 'squat', 'compound', 'intermediate'],
  ['front-squat', 'Front Squat', 'quads', ['glutes', 'abs'], 'barbell', 'squat', 'compound', 'advanced'],
  ['goblet-squat', 'Goblet Squat', 'quads', ['glutes'], 'dumbbell', 'squat', 'compound', 'beginner'],
  ['leg-press', 'Leg Press', 'quads', ['glutes'], 'machine', 'squat', 'compound', 'beginner'],
  ['hack-squat', 'Hack Squat', 'quads', ['glutes'], 'machine', 'squat', 'compound', 'intermediate'],
  ['bulgarian-split-squat', 'Bulgarian Split Squat', 'quads', ['glutes', 'hamstrings'], 'dumbbell', 'lunge', 'compound', 'intermediate'],
  ['lunge', 'Reverse Lunge', 'quads', ['glutes', 'hamstrings'], 'dumbbell', 'lunge', 'compound', 'beginner'],
  ['walking-lunge', 'Walking Lunge', 'quads', ['glutes'], 'dumbbell', 'lunge', 'compound', 'beginner'],
  ['step-up', 'Step-up', 'quads', ['glutes'], 'dumbbell', 'lunge', 'compound', 'beginner'],
  ['leg-extension', 'Leg Extension', 'quads', [], 'machine', 'isolation', 'isolation', 'beginner'],
  ['conventional-deadlift', 'Conventional Deadlift', 'hamstrings', ['glutes', 'lower-back', 'traps'], 'barbell', 'hinge', 'compound', 'intermediate'],
  ['romanian-deadlift', 'Romanian Deadlift', 'hamstrings', ['glutes', 'lower-back'], 'barbell', 'hinge', 'compound', 'intermediate'],
  ['sumo-deadlift', 'Sumo Deadlift', 'glutes', ['quads', 'adductors', 'hamstrings'], 'barbell', 'hinge', 'compound', 'intermediate'],
  ['trap-bar-deadlift', 'Trap-Bar Deadlift', 'quads', ['glutes', 'hamstrings', 'traps'], 'barbell', 'hinge', 'compound', 'beginner'],
  ['lying-leg-curl', 'Lying Leg Curl', 'hamstrings', [], 'machine', 'isolation', 'isolation', 'beginner'],
  ['seated-leg-curl', 'Seated Leg Curl', 'hamstrings', [], 'machine', 'isolation', 'isolation', 'beginner'],
  ['nordic-curl', 'Nordic Curl', 'hamstrings', [], 'bodyweight', 'isolation', 'isolation', 'advanced'],
  ['kettlebell-swing', 'Kettlebell Swing', 'glutes', ['hamstrings', 'lower-back'], 'kettlebell', 'hinge', 'compound', 'beginner'],
  ['hip-thrust', 'Hip Thrust', 'glutes', ['hamstrings'], 'barbell', 'hinge', 'compound', 'beginner'],
  ['glute-bridge', 'Glute Bridge', 'glutes', ['hamstrings'], 'bodyweight', 'hinge', 'isolation', 'beginner'],
  ['cable-kickback', 'Cable Kickback', 'glutes', [], 'cable', 'isolation', 'isolation', 'beginner'],
  ['standing-calf-raise', 'Standing Calf Raise', 'calves', [], 'machine', 'isolation', 'isolation', 'beginner'],
  ['seated-calf-raise', 'Seated Calf Raise', 'calves', [], 'machine', 'isolation', 'isolation', 'beginner'],
  ['hip-adduction', 'Hip Adduction', 'adductors', [], 'machine', 'isolation', 'isolation', 'beginner'],
  ['plank', 'Plank', 'abs', ['obliques'], 'bodyweight', 'core', 'isolation', 'beginner'],
  ['crunch', 'Crunch', 'abs', [], 'bodyweight', 'core', 'isolation', 'beginner'],
  ['hanging-leg-raise', 'Hanging Leg Raise', 'abs', ['obliques'], 'bodyweight', 'core', 'isolation', 'intermediate'],
  ['cable-crunch', 'Cable Crunch', 'abs', [], 'cable', 'core', 'isolation', 'beginner'],
  ['ab-wheel', 'Ab Wheel', 'abs', ['obliques', 'lats'], 'bodyweight', 'core', 'compound', 'intermediate'],
  ['side-plank', 'Side Plank', 'obliques', ['abs'], 'bodyweight', 'core', 'isolation', 'beginner'],
  ['pallof-press', 'Pallof Press', 'obliques', ['abs'], 'cable', 'core', 'isolation', 'beginner'],
  ['russian-twist', 'Russian Twist', 'obliques', ['abs'], 'bodyweight', 'core', 'isolation', 'beginner'],
];

export const FALLBACK_CATALOG: CatalogExercise[] = ROWS.map(
  ([slug, name, primaryMuscle, secondaryMuscles, equipment, pattern, type, difficulty]) => ({
    id: slug,
    slug,
    name,
    primaryMuscle,
    secondaryMuscles,
    equipment,
    pattern,
    type,
    difficulty,
  }),
);
